name = "calendar-ripper-favorites"
main = "src/index.ts"
compatibility_date = "2026-02-01"

[vars]
GITHUB_PAGES_BASE_URL = "https://prestomation.github.io/calendar-ripper"
SITE_URL = "https://prestomation.github.io/calendar-ripper"

[[kv_namespaces]]
binding = "USERS"
id = "d0c3c4e0a14c4a4284de09de18a1136f"

[[kv_namespaces]]
binding = "FAVORITES"
id = "d3d850c6081a4a0490e1e02c34e1c231"

[[kv_namespaces]]
binding = "FEED_TOKENS"
id = "d798d8ad13214ade84fd5692532a7993"
